name: driverojek
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"   #">=2.1.0 <3.0.0"    

dependencies:
  flutter:
    sdk: flutter 
 
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  google_maps_flutter: ^0.5.25 #0.5.21+1  0.5.21+8
 
  # Add the following two lines
  http: ^0.12.0+4  # 0.12.0+2   0.12.0+1  0.12.0+4
  shared_preferences:       #^0.5.6+3 
  font_awesome_flutter: ^8.7.0 #8.7.0 8.2.0
   
  sliding_up_panel: ^1.0.1 
  geolocator: ^5.3.1 
  #location: ^3.0.2
  permission: ^0.1.7 

  intl: ^0.15.7
  
  #rxdart: ^0.24.1


  expandable_bottom_sheet: ^0.2.1+1
  #firebase
  firebase_messaging: ^6.0.15   #^6.0.12   #^6.0.15  ^6.0.13
  cloud_firestore: ^0.13.4 #^0.13.5 
  firebase_auth: ^0.16.0  #0.14.0+5    
  firebase_storage: ^3.0.6 
  
  #notifications
  flutter_local_notifications: ^1.4.1 

  #sound player
  flutter_ringtone_player: ^2.0.0 

  #uri launcer
  url_launcher: ^5.4.5

  #webview_flutter 
  webview_flutter: ^0.3.21

  #share button
  share: ^0.6.4+1

  #launch_review: playstore
  launch_review: ^2.0.0

  #flutter geo location by radius
  #geoflutterfire: ^2.1.0  
  
  #paging
  #flutter_paginator: ^0.0.6  
  
  image_picker: ^0.6.1+8 
  
  #fluttertoast: ^4.0.0

  #dicurigai berat

  #cached_network_image: ^2.2.0+1
  #rxdart: ^0.24.1   
  #flutter_ringtone_player: ^2.0.0   
  fluttertoast: ^4.0.1   #fluttertoast: ^4.0.1
  flutter_rating_bar: ^3.0.1+1
 
  cached_network_image: 2.0.0-rc.1

  photo_view: ^0.9.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.4.0
  build_runner: ^1.2.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:  
    - assets/
    - assets/images/
    - assets/images/chat/
    - assets/images/bank/
    - assets/images/topup/
    - assets/img_logo.png 
    - assets/images/no_inbox.png
    #untuk chat
    - assets/images/chat/img_not_available.jpeg
    - assets/images/chat/mimi1.gif
    - assets/images/chat/mimi2.gif
    - assets/images/chat/mimi3.gif
    - assets/images/chat/mimi4.gif
    - assets/images/chat/mimi5.gif
    - assets/images/chat/mimi6.gif
    - assets/images/chat/mimi7.gif
    - assets/images/chat/mimi8.gif
    - assets/images/chat/mimi9.gif
    #bank
    - assets/images/bank/bni.png
    - assets/images/bank/bri.png
    #bank
    - assets/images/topup/topup.png 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
